name: flutter_jcp_core
description: "Flutter Package by Josh Cho"
version: 1.0.0
homepage: https://github.com/whdudqls1997

publish_to: 'none'

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
